package com.samangkar.Samangkar.service;

public class UserReviewService {

    //GET USER REVIEW BY SHOP ID => WHERE IS IS_DELETE = FALSE

    //INSERT REVIEW BY SHOP_ID AND USER_ID

    //UPDATE REVIEW BY SHOP_ID AND USER_ID => SET DESCRIPRTION , LAST_MODIFIED_DATE = NOW , IS_UPDATE = TRUE.
    
    //DELTE REVIEW => SET IS_DELETE TO TRUE


}
